spring:
  application:
    name: kyc-customers-users
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
    external-services:
      enabled: true
  info:
    build:
      enabled: false

kyc-messages:
  catalog:
    messages:
      "001":
        code: KYC-CUSTOMER-USERS-001
        message: Unexpected Error
        type: ERROR
      "002":
        code: KYC-CUSTOMER-USERS-002
        message: The request is invalid
        type: ERROR
      "003":
        code: KYC-CUSTOMER-USERS-003
        message: The provided credentials are invalid
        type: ERROR
      "004":
        code: KYC-CUSTOMER-USERS-004
        message: The password entered does not meet the conditions. No same as the username, one upper case letter, one digit and one special character.
        type: ERROR
      "005":
        code: KYC-CUSTOMER-USERS-005
        message: It is not possible to create the username
        type: WARN
      "006":
        code: KYC-CUSTOMER-USERS-006
        message: The username or password is incorrect
        type: ERROR
      "007":
        code: KYC-CUSTOMER-USERS-007
        message: The user is not valid
        type: ERROR
      "008":
        code: KYC-CUSTOMER-USERS-008
        message: The user is inactive or is locked
        type: ERROR
      "009":
        code: KYC-CUSTOMER-USERS-009
        message: There is already an active session for this channel
        type: WARN
      "010":
        code: KYC-CUSTOMER-USERS-010
        message: The operation cannot be perfomed at the moment
        type: ERROR
      "011":
        code: KYC-CUSTOMER-USER-011
        message: The session already has expired
        type: ERROR
      "012":
        code: KYC-CUSTOMER-USER-012
        message: Welcome to KYC Platform
        type: INFO

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

